# Etapa 1: Construcción (Build)
FROM node:20-alpine AS build
WORKDIR /app

# Ajuste de memoria para evitar que el build de Angular falle en servidores pequeños
ENV NODE_OPTIONS="--max-old-space-size=2048"

# Evitar errores de red/timeout en npm
RUN npm config set registry https://registry.npmjs.org/ && \
    npm config set fetch-retry-maxtimeout 120000

COPY package*.json ./
RUN npm install

COPY . .

# Generar los archivos estáticos de Angular
# Nota: Usamos el environment.ts que tiene apiUrl: '/api'
RUN npm run build

# Etapa 2: Servidor Web (Nginx)
FROM nginx:stable-alpine

# Copiamos la configuración del Proxy Inverso
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiamos el build final (ajustado a tu carpeta 'browser' que vimos en la imagen)
COPY --from=build /app/dist/FrontEnd/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]