# Etapa 1: Construcción (Build)
FROM node:20-alpine AS build
WORKDIR /app

# Aumentamos la memoria asignada a Node para evitar que el build falle
ENV NODE_OPTIONS="--max-old-space-size=2048"

# Copiamos archivos de dependencias
COPY package*.json ./

# Instalamos dependencias limpias
RUN npm ci || npm install

# Copiamos todo el código
COPY . .

# Ejecutamos el build. 
# Si tu configuración está en environment.ts, usa este comando:
RUN npm run build -- --output-path=dist/FrontEnd

# Etapa 2: Servidor Web (Nginx)
FROM nginx:stable-alpine

# Borramos la configuración por defecto de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiamos nuestra configuración (el proxy inverso)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiamos los archivos generados. 
# OJO: Verifica si la ruta es /app/dist/FrontEnd/browser o solo /app/dist/FrontEnd
COPY --from=build /app/dist/FrontEnd/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]