version: "3.8"

services:
  # --- BASE DE DATOS ---
  db:
    image: postgres:15-alpine
    container_name: vox-db-prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    networks:
      - vox-net-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- BACKEND ---
  backend:
    build: ./back-end
    container_name: vox-api-prod
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - vox-net-prod

  # --- FRONTEND (Angular + Nginx) ---
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: dockerfile # Tu archivo en minúsculas
    container_name: vox-front-prod
    depends_on:
      - backend
    networks:
      - vox-net-prod

  # --- NGROK ---
  ngrok:
    image: ngrok/ngrok:latest
    container_name: vox-ngrok-prod
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "frontend:80"
    networks:
      - vox-net-prod
    depends_on:
      - frontend

networks:
  vox-net-prod:
    driver: bridge

volumes:
  pg_data_prod: